spring.application.name=eureka

server.port=8761
# Actua como cliente y servidor, lo cual pedimos que no se tenga que registrar a si mismo.
eureka.client.register-with-eureka=false

eureka.client.fetch-registry=false
# Le indicamos que optenga las ip y no los nombres del dominio
eureka.instance.prefer-ip-address=true